default: &default
  adapter: solid_cable
  polling_interval: 1.second
  keep_messages_around_for: 1.day
  connects_to:
    database:
      writing: cable

development:
  <<: *default
  silence_polling: true

test:
  <<: *default

production:
  <<: *default
  polling_interval: 0.1.seconds
